export const MARK_NOTIFICATIONS_BY_ID = Symbol()
export const MARK_NOTIFICATIONS = Symbol()
export const START_NOTIFICATIONS = Symbol()
export const END_NOTIFICATIONS = Symbol()
export const RECEIVE_NOTIFICATIONS = Symbol()
export const STARTLOGIN = Symbol()
export const LOGINSUCCSESS = Symbol()
export const LOGINFAILED = Symbol()